Repository microsoft/DirectXTK12, pull requests merged in 2024-02, with the labels that each got.

#210 Update GDK projects and ADO pipelines
  DirectXTK_GDK_2019.vcxproj
  DirectXTK_GDK_2022.vcxproj
  build/DirectXTK12-OneFuzz.yml
Labels: maintainence

#211 Workaround clang/LLVM bug with /fp:fast+SSE+float_control
  Audio/AudioEngine.cpp
  Audio/DynamicSoundEffectInstance.cpp
  Audio/SoundStreamInstance.cpp
  Audio/WaveBankReader.cpp
  CMakeLists.txt
  Src/Keyboard.cpp
  Src/LoaderHelpers.h
  Src/Mouse.cpp
  Src/d3dx12.h
Labels: conformance

#208 fix warning for MSVC pragma syntax.
  Audio/AudioEngine.cpp
  Audio/DynamicSoundEffectInstance.cpp
  Audio/SoundStreamInstance.cpp
  Audio/WaveBankReader.cpp
  Inc/Audio.h
  Inc/DirectXHelpers.h
  Inc/GamePad.h
  Inc/Keyboard.h
  Inc/Mouse.h
  Inc/ScreenGrab.h
  Inc/WICTextureLoader.h
  Src/GamePad.cpp
  Src/Keyboard.cpp
  Src/Mouse.cpp
  Src/PlatformHelpers.h
  Src/pch.h
Labels: conformance

#212 Update CMake to work with Intel compilers
  CMakeLists.txt
  CMakePresets.json
  Inc/GamePad.h
  Inc/Keyboard.h
  Inc/Mouse.h
  Src/WICTextureLoader.cpp
Labels: conformance

#213 CMake refactor
  CMakeLists.txt
  DirectXTK_Desktop_2019_Win10.vcxproj
  DirectXTK_Desktop_2022_Win10.vcxproj
  DirectXTK_GDK_2019.vcxproj
  DirectXTK_GDK_2022.vcxproj
  DirectXTK_Windows10_2019.vcxproj
  DirectXTK_Windows10_2022.vcxproj
  Src/pch.h
  build/CompilerAndLinker.cmake
Labels: maintainence

#215 February 21, 2024
  .nuget/directxtk12_desktop_2019.nuspec
  .nuget/directxtk12_uwp.nuspec
  CMakeLists.txt
  HISTORY.md
  README.md
Labels: maintainence

#216 Hotfix for CMake switch order
  build/CompilerAndLinker.cmake
Labels: bug
