Repository microsoft/DirectXTK12, pull requests merged in 2025-04, with the labels that each got.

#319 Migrate ADO pipelines to .azuredevops folder
  .azuredevops/pipelines/DirectXTK12-GitHub-CMake-Dev17.yml
  .azuredevops/pipelines/DirectXTK12-GitHub-CMake.yml
  .azuredevops/pipelines/DirectXTK12-GitHub-Dev17.yml
  .azuredevops/pipelines/DirectXTK12-GitHub-GDK-Dev17.yml
  .azuredevops/pipelines/DirectXTK12-GitHub-GDK.yml
  .azuredevops/pipelines/DirectXTK12-GitHub-MinGW.yml
  .azuredevops/pipelines/DirectXTK12-GitHub-SDK-prerelease.yml
  .azuredevops/pipelines/DirectXTK12-GitHub-SDK-release.yml
  .azuredevops/pipelines/DirectXTK12-GitHub-Test-Dev17.yml
  .azuredevops/pipelines/DirectXTK12-GitHub-Test.yml
  .azuredevops/pipelines/DirectXTK12-GitHub.yml
  .azuredevops/pipelines/DirectXTK12-OneFuzz-Coverage.yml
  .azuredevops/pipelines/DirectXTK12-OneFuzz.yml
  .azuredevops/pipelines/DirectXTK12-SDL.yml
  .github/workflows/codeql.yml
  .github/workflows/main.yml
  .github/workflows/msbuild.yml
  .github/workflows/msvc.yml
  .github/workflows/test.yml
  .github/workflows/uwp.yml
  .github/workflows/vcpkg.yml
Labels: maintenance

#323 Update ADL YAML to use shared variables
  .azuredevops/pipelines/DirectXTK12-GitHub-GDK-Dev17.yml
  .azuredevops/pipelines/DirectXTK12-GitHub-GDK.yml
  .azuredevops/pipelines/DirectXTK12-GitHub-MinGW.yml
  .azuredevops/pipelines/DirectXTK12-GitHub-SDK-prerelease.yml
  .azuredevops/pipelines/DirectXTK12-GitHub-SDK-release.yml
  .azuredevops/pipelines/DirectXTK12-GitHub-Test-Dev17.yml
  .azuredevops/pipelines/DirectXTK12-GitHub-Test.yml
Labels: azure_pipelines

#322 Change the way GameInput callbacks are handled for mouse/keyboard
  Src/Keyboard.cpp
  Src/Mouse.cpp
Labels: input
