Repository microsoft/DirectXTK12, pull requests merged in 2025-01, with the labels that each got.

#296 Code review for Mouse CoreWindow implementation
  Src/Mouse.cpp
Labels: maintenance, input

#297 CMake update to fix cases where DIRECTX_ARCH is not defined
  build/CompilerAndLinker.cmake
Labels: cmake

#298 Update VCPKG GHAs to use head commit id if variable isn't set
  .github/workflows/vcpkg.yml
Labels: maintenance
